//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public byte[] user_pass { get; set; }
        public string user_email { get; set; }
    }
}
