//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belina.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BelinaEntities2 : DbContext
    {
        public BelinaEntities2()
            : base("name=BelinaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attributes> Attributes { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Company_Class> Company_Class { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Type> Type { get; set; }
        public DbSet<Type_Company> Type_Company { get; set; }
        public DbSet<Administrator> Administrator { get; set; }
        public DbSet<Product_Attribute> Product_Attribute { get; set; }
    }
}
