//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Type
    {
        public Nullable<int> class_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public int id { get; set; }
    }
}
