//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string product_name { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> attribute_id { get; set; }
        public int product_id { get; set; }
        public string product_description { get; set; }
        public string product_promotion { get; set; }
        public string product_discount { get; set; }
        public string product_image { get; set; }
    }
}
